#!/bin/bash
BASEDIR=$(dirname $(readlink -f "$0"))
(
    cd "$BASEDIR"
    source .env
    export DOCKER_HOST
    docker run -it --rm \
        -v "${COMPOSE_PROJECT_NAME}_certificates:/etc/letsencrypt" \
        certbot/certbot "$@"
)